Repository KwanLab/Autometa, pull requests merged in 2020-06, with the labels that each got.

#94 Fix taxid parsing
  pipeline/cluster_taxonomy.py
Labels: hotfix

#90 verbose bug
  autometa/common/external/hmmer.py
  autometa/common/external/prodigal.py
Labels: bug

#84 Recursive DBSCAN
  autometa/binning/recursive_dbscan.py
  autometa/common/exceptions.py
  autometa/config/user.py
Labels: bug, code review, documentation

#77 databases and utilities
  .condarc.yaml
  .gitignore
  autometa/common/utilities.py
  autometa/config/databases.py
  autometa/config/default.config
  autometa/databases/markers/archaea.single_copy.cutoffs.md5
  autometa/databases/markers/archaea.single_copy.hmm.md5
  autometa/databases/markers/bacteria.single_copy.cutoffs.md5
  autometa/databases/markers/bacteria.single_copy.hmm.md5
Labels: code review, documentation, enhancement

#87 diamond.py
  autometa/common/external/diamond.py
  docs/parse_argparse.py
  docs/source/conf.py
Labels: code review, documentation
