Repository KwanLab/Autometa, pull requests merged in 2020-05, with the labels that each got.

#62 Add Markers class documentation.
  autometa/common/markers.py
Labels: documentation

#63 Add __main__.py documentation (fixes #60)
  autometa/__main__.py
Labels: documentation, enhancement

#65 Add functionality to bin without taxonomy. Update docstrings
  autometa/config/__init__.py
  autometa/config/metagenome.config
  autometa/config/user.py
Labels: documentation, enhancement

#45 Documentation
  .gitignore
  .readthedocs.yaml
  autometa/common/exceptions.py
  autometa/common/external/bedtools.py
  autometa/common/external/diamond.py
  autometa/common/external/hmmer.py
  autometa/common/external/prodigal.py
  autometa/common/external/samtools.py
  autometa/common/external/work_queue.py
  autometa/common/markers.py
  autometa/common/utilities.py
  autometa/config/databases.py
  autometa/config/environ.py
  autometa/config/project.py
  autometa/config/user.py
  autometa/taxonomy/lca.py
  autometa/taxonomy/majority_vote.py
  autometa/taxonomy/ncbi.py
  autometa/validation/cluster_process.py
  docs/README.md
  docs/environment.yaml
  docs/parse_argparse.py
  docs/requirements.txt
  docs/source/Scripts/Binning/binning.rst
  docs/source/Scripts/Binning/recursive_dbscan.rst
  docs/source/Scripts/Common/External/bedtools.rst
  docs/source/Scripts/Common/External/bowtie.rst
  docs/source/Scripts/Common/External/diamond.rst
  docs/source/Scripts/Common/External/external.rst
  docs/source/Scripts/Common/External/hmmer.rst
  docs/source/Scripts/Common/External/prodigal.rst
  docs/source/Scripts/Common/External/samtools.rst
  docs/source/Scripts/Common/External/work_queue.rst
  docs/source/Scripts/Common/common.rst
  docs/source/Scripts/Common/coverage.rst
  docs/source/Scripts/Common/exceptions.rst
  docs/source/Scripts/Common/kmers.rst
  docs/source/Scripts/Common/mag.rst
  docs/source/Scripts/Common/markers.rst
  docs/source/Scripts/Common/metagenome.rst
  docs/source/Scripts/Common/utilities.rst
  docs/source/Scripts/Config/config.rst
  docs/source/Scripts/Config/databases.rst
  docs/source/Scripts/Config/environ.rst
  docs/source/Scripts/Config/project.rst
  docs/source/Scripts/Config/user.rst
  docs/source/Scripts/Taxonomy/lca.rst
  docs/source/Scripts/Taxonomy/majority_vote.rst
  docs/source/Scripts/Taxonomy/ncbi.rst
  docs/source/Scripts/Taxonomy/taxonomy.rst
  docs/source/Scripts/Validation/cluster_process.rst
  docs/source/Scripts/Validation/validation.rst
  docs/source/Scripts/autometa.rst
  docs/source/Scripts/datasets.rst
  docs/source/Scripts/scripts.rst
  docs/source/conf.py
  docs/source/contribution-guidelines.rst
  docs/source/examining-results.rst
  docs/source/index.rst
Labels: documentation

#69 Remove merge conflict resolution lines (Fixes #68)
  autometa/common/markers.py
Labels: bug

#76 :art: :racehorse: Resolves #55
  autometa/config/environ.py
Labels: code review

#66 fixes-#54 Metagenome
  autometa/common/mag.py
  autometa/common/metagenome.py
  autometa/taxonomy/ncbi.py
  docs/template.py
Labels: bug, documentation, enhancement

#72 hmmer
  autometa/common/external/hmmer.py
Labels: code review

#78 LCA
  autometa/common/kmers.py
  autometa/taxonomy/lca.py
Labels: code review, documentation

#81 Update majority_vote
  autometa/taxonomy/majority_vote.py
Labels: code review, documentation, enhancement
