Repository KwanLab/Autometa, pull requests merged in 2020-09, with the labels that each got.

#107 Dockerfile path bugfix
  Dockerfile
Labels: bug

#83 ncbi.py
  autometa/__main__.py
  autometa/binning/recursive_dbscan.py
  autometa/common/exceptions.py
  autometa/common/external/diamond.py
  autometa/taxonomy/ncbi.py
  docs/source/databases.rst
Labels: code review, documentation

#103 Samtools
  autometa/common/coverage.py
  autometa/common/exceptions.py
  autometa/common/external/samtools.py
Labels: code review

#100 decision tree classifier
  autometa/binning/unclustered_recruitment.py
Labels: code review

#104 Fix config and setup of user project
  .gitignore
  autometa/__main__.py
  autometa/binning/recursive_dbscan.py
  autometa/binning/summary.py
  autometa/binning/unclustered_recruitment.py
  autometa/common/coverage.py
  autometa/common/exceptions.py
  autometa/common/external/bedtools.py
  autometa/common/external/bowtie.py
  autometa/common/external/diamond.py
  autometa/common/external/hmmer.py
  autometa/common/external/prodigal.py
  autometa/common/kmers.py
  autometa/common/markers.py
  autometa/common/metabin.py
  autometa/common/metagenome.py
  autometa/common/utilities.py
  autometa/config/__init__.py
  autometa/config/databases.py
  autometa/config/default.config
  autometa/config/environ.py
  autometa/config/metagenome.config
  autometa/config/project.py
  autometa/config/user.py
  autometa/taxonomy/lca.py
  autometa/taxonomy/vote.py
  setup.py
  tests/autometa.mf
  tests/metagenome.config
Labels: bug, enhancement
