Repository KwanLab/Autometa, pull requests merged in 2022-01, with the labels that each got.

#206 Fix/Create mock data subworkflow
  .github/workflows/linting.yml
  Makefile
  bin/clean_mock_data.sh
  conf/modules.config
  docker/modules/get_genomes_for_mock.Dockerfile
  docker/modules/mock_data_reporter.Dockerfile
  lib/mock_data_report.Rmd
  modules/local/get_genomes_for_mock.nf
  modules/local/mock_data_reporter.nf
  subworkflows/local/mock_data.nf
  workflows/autometa.nf
Labels: nextflow

#212 :memo: Update Documentation
  docs/source/conf.py
  docs/source/contribution-guidelines.rst
  docs/source/index.rst
Labels: documentation

#208 :art: Add typehints and update kmers docstring
  autometa/common/external/diamond.py
  autometa/common/kmers.py
Labels: documentation, python

#201 :art::snake: Add specific parsers for domtblout and tblout for hmmscan output formats
  autometa/common/external/hmmscan.py
  autometa/common/markers.py
  tests/unit_tests/test_markers.py
Labels: enhancement, python

#210 :snake::art::bug: Update metagenome.length_filter(...)
  autometa/common/metagenome.py
Labels: python

#209 Fix bedtools genomecov deprecation (coverage calculation)
  autometa/common/coverage.py
  autometa/common/external/bedtools.py
  modules/local/parse_bed.nf
  setup.py
  tests/unit_tests/test_coverage.py
Labels: nextflow, python

#202 :art:🐚 Add bash-implementations of Autometa workflows
  workflows/autometa.sh
Labels: enhancement

#184 Nextflow documentation
  docs/source/running-autometa.rst
Labels: documentation, nextflow

#211 Refactor autometa-taxonomy-lca
  autometa/common/markers.py
  autometa/taxonomy/lca.py
  autometa/taxonomy/majority_vote.py
  autometa/taxonomy/ncbi.py
  autometa/taxonomy/vote.py
  modules/local/prepare_lca.nf
  modules/local/reduce_lca.nf
  subworkflows/local/bin_contigs.nf
  subworkflows/local/lca.nf
  subworkflows/local/taxon_assignment.nf
  workflows/autometa.sh
Labels: nextflow, python
