Repository KwanLab/Autometa, pull requests merged in 2023-08, with the labels that each got.

#340 :fire::whale::green_heart: Fix docker-builds by removing pinned dependencies
  .github/workflows/docker_autometa.yml
  Dockerfile
  autometa-env.yml
Labels: bug, hotfix, continuous integration

#341 💚:bug::snake: Fix bug for 0 passing predictions
  Makefile
  autometa-env.yml
  autometa/binning/recursive_dbscan.py
  autometa/binning/unclustered_recruitment.py
  docs/source/bash-workflow.rst
  docs/source/benchmarking.rst
  docs/source/how-to-contribute.rst
  docs/source/installation.rst
  docs/source/nextflow-workflow.rst
  docs/source/step-by-step-tutorial.rst
  tests/environment.yml
Labels: bug, python, continuous integration

#329 :bug: Fix GTDB database setup
  autometa/taxonomy/gtdb.py
Labels: bug

#339 :bug::shell: Fix GTDB taxon-binning workflow
  workflows/autometa-large-data-mode.sh
  workflows/autometa.sh
Labels: bug

#342 📝 Update documentation
  docs/source/autometa-python-api.rst
  docs/source/bash-step-by-step-tutorial.rst
  docs/source/index.rst
Labels: documentation

#325 :snake::art::fire::bug: Fix UnboundLocalError bug
  autometa/binning/large_data_mode.py
Labels: bug

#343 :bug::art::snake: Refactor 'unclassified' handling
  autometa/taxonomy/database.py
  autometa/taxonomy/vote.py
Labels: bug
